# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spider?&serverTimezone=UTC
    username: root
    password: 123456
    hikari:
      max-lifetime: 1500000
      connection-timeout: 30000
      idle-timeout: 30000
      pool-name: SpringBootHikariCP
      maximum-pool-size: 8
      minimum-idle: 3

  redis:
    # Redis数据库索引（默认为0）
    database: 1
    host: 47.98.253.2
    port: 6379
    password:
    lettuce:
      shutdown-timeout: 100 # 关闭超时时间
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        max-wait: 30 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 10000 #连接超时的时间
  profiles:
    active: test

logging:
  level:
    com.aaa.mapper: debug
server:
  worker-id: 5
  data-center-id: 6
  port: 8070
