# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spider?&serverTimezone=UTC
    username: root
    password: 123456
    hikari:
      max-lifetime: 1500000
      connection-timeout: 30000
      idle-timeout: 30000
      pool-name: SpringBootHikariCP
      maximum-pool-size: 8
      minimum-idle: 3


